# Generated by Django 2.2.5 on 2019-09-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_game_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='image_url',
            field=models.CharField(max_length=100),
        ),
    ]
