# Generated by Django 2.2.5 on 2019-11-07 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20191031_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyPlayed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='games.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='games.RegisterUser')),
            ],
        ),
    ]
