# Generated by Django 2.2.5 on 2019-11-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_recentlyplayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentlyplayed',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
